### ISSUE TITLE
Upgrade Mailinabox Quota to this new repo - possible ?

### ISSUE THREAD

**Issue by uksitebuilder** [jrsupplee/mailinabox-extra#1]
Hi

Currently using your excellent repo with the Quotas addition, updated to latest version.

Is it possible to move over to this version with the extras features?

**Comment by jrsupplee** [comment]
You can switch to the new repository without any data changes.  Follow the instructions in the README

**Comment by uksitebuilder** [comment]
Thanks

**Comment by uksitebuilder** [comment]
Just a FYi, on the Status Screen, get the following when using extra version

```
A new version of Mail-in-a-Box is available. You are running version v0.43-extra-0.10-beta.
The latest version is v0.43-quota-0.21-beta. For upgrade instructions, see https://github.com/jrsupplee/mailinabox/blob/master/README.md.
```

Feel free to close this now

**Comment by jrsupplee** [comment]
Fixed this problem and released a new version.  I also removed the POSTSRSD option as it was causing a problem on one of my servers.

**Comment by uksitebuilder** [comment]
I thought it went well.

Admin loads up fine

Details presented for the mailboxes etc look fine as normal.

However, unable to receive any new emails or send any mails now

**Comment by jrsupplee** [comment]
Did you solve this problem?  Try rebooting the machine.  Maybe a problem with DNS.  Need more details

**Comment by uksitebuilder** [comment]
Still trying to solve.  All status page comes back fine.  DNS has not been changed,  rebooted several times. :-(

**Comment by jrsupplee** [comment]
I found the issue I will have a patch soon

**Comment by uksitebuilder** [comment]
That would be great.  I have tried updating to your quota distro without extras but still unable to send/receive mail

Fingers crossed your patch works 

If not, I will have to spin up a new Droplet at DO and import user_data from backup or rsync it over

**Comment by jrsupplee** [comment]
I released a new version that will solve the problem.  You will need to go back to the extra repository for the patch to work.

If you want to stay with the quotas only repository then you need to execute the following command from the command line:

    sudo postconf -X sender_canonical_maps sender_canonical_classes recipient_canonical_maps recipient_canonical_classes

then restart postfix just to be sure (systemctl restart postfix)

sorry for the issues

**Comment by uksitebuilder** [comment]
That seems to have done the trick.   Thanks for the speedy fix
