### ISSUE TITLE
Does upgrading resets default/user quota ?

### ISSUE THREAD

**Issue by shubhank008** [jrsupplee/mailinabox-extra#6]
As the title says, do updating to newer version in future (say 0.53) will reset the default quota back to 0 and same with user quotas ?    
Like if I have set 15GB default quota and some user has 20GB quota set manually, will both those changes be lost on each upgrade ?

**Comment by jrsupplee** [comment]
No it should not.

Were the quotas reset in your install?

**Comment by shubhank008** [comment]
Nope, was just a curiosity question. Thanks for the quick reply.
